import SwiftUI
import ResetFoundation
import ResetCore

struct ResetProgressView: View {
    let session: ResetSession
    @State private var selected: Date?
    @State private var expanded = false
    var body: some View { ScrollView(showsIndicators: false) { VStack(alignment: .leading, spacing: 18) {
        HStack(alignment: .bottom) { VStack(alignment: .leading, spacing: 3) { Text("Your rhythm").font(.largeTitle.bold()); Text("Every clear surface leaves a little more calm.").foregroundStyle(FoundationTokens.muted) }; Spacer(); CompanionView(mood: .calm, accent: ResetTokens.accent).frame(width: 72, height: 72) }
        HStack(alignment: .firstTextBaseline) { Text("\(session.progress.streak)").font(.system(size: 48, weight: .bold, design: .rounded)).foregroundStyle(ResetTokens.accent); Text("day streak").font(.headline); Spacer(); Text("Level \(session.progress.level) · \(session.progress.total) resets").font(.subheadline.weight(.semibold)).foregroundStyle(FoundationTokens.muted) }
        ResetHistoryStrip(progress: session.progress, expanded: $expanded, selected: $selected)
        HStack(alignment: .top, spacing: 18) { ResetMilestone(symbol: session.progress.total >= 3 ? "leaf.fill" : "sparkle", title: "3 resets", detail: session.progress.total >= 3 ? "Plant on the desk" : "Plant detail"); Rectangle().fill(ResetTokens.accent.opacity(0.25)).frame(height: 2).padding(.top, 14); ResetMilestone(symbol: session.progress.total >= 7 ? "sun.max.fill" : "lock.fill", title: "7 resets", detail: session.progress.total >= 7 ? "A calmer corner" : "\(session.progress.total)/7") }
    }.padding(20) }.background(ResetTokens.wash).sheet(item: $selected) { date in ResetDateDetail(date: date, completed: session.progress.history.contains(ResetDay.key(date)), canCorrect: date < Date()) { session.perform { try $0.complete(on: date) }; selected = nil } } }
}
struct ResetHistoryStrip: View { let progress: ResetProgress; @Binding var expanded: Bool; @Binding var selected: Date?; var body: some View { VStack(alignment: .leading, spacing: 12) { HStack { Text(expanded ? "History" : "This week").font(.headline); Spacer(); Button(expanded ? "Compact" : "Expand") { withAnimation(.spring(response: 0.35)) { expanded.toggle() } }.buttonStyle(.plain).foregroundStyle(ResetTokens.accent) }; if expanded { LazyVGrid(columns: Array(repeating: GridItem(.flexible()), count: 7), spacing: 12) { ForEach(Array((0..<28).reversed()), id: \.self) { offset in let date = Calendar.current.date(byAdding: .day, value: -offset, to: Date())!; ResetDayDot(date: date, completed: progress.history.contains(ResetDay.key(date)), selected: $selected) } } } else { HStack(spacing: 8) { ForEach((-3...3), id: \.self) { offset in let date = Calendar.current.date(byAdding: .day, value: offset, to: Date())!; ResetDayDot(date: date, completed: progress.history.contains(ResetDay.key(date)), selected: $selected) } }.frame(maxWidth: .infinity) } } } }
private struct ResetDayDot: View { let date: Date; let completed: Bool; @Binding var selected: Date?; var body: some View { Button { selected = date } label: { VStack(spacing: 7) { Text(date, format: .dateTime.weekday(.narrow)).font(.caption2.weight(.semibold)).foregroundStyle(FoundationTokens.muted); Circle().fill(completed ? ResetTokens.accent : date > Date() ? FoundationTokens.surface : ResetTokens.accent.opacity(0.12)).frame(width: 34, height: 34).overlay { if completed { Image(systemName: "checkmark").font(.caption.bold()).foregroundStyle(.white) } else { Text(date, format: .dateTime.day()).font(.caption.weight(.semibold)) } } } }.buttonStyle(.plain).accessibilityLabel("\(date.formatted(date: .complete, time: .omitted)), \(completed ? "completed" : date > Date() ? "future" : "missed")") } }
private struct ResetMilestone: View { let symbol: String; let title: String; let detail: String; var body: some View { VStack(alignment: .leading, spacing: 5) { Image(systemName: symbol).font(.title3).foregroundStyle(ResetTokens.accent); Text(title).font(.subheadline.weight(.semibold)); Text(detail).font(.caption).foregroundStyle(FoundationTokens.muted) } } }
struct ResetDateDetail: View, Identifiable { let date: Date; let completed: Bool; let canCorrect: Bool; let correct: () -> Void; var id: Date { date }; var body: some View { VStack(spacing: 15) { Capsule().fill(ResetTokens.accent.opacity(0.25)).frame(width: 38, height: 5); Text(date, format: .dateTime.weekday(.wide).month(.wide).day()).font(.title2.bold()); Image(systemName: completed ? "sparkles" : "square.and.pencil").font(.system(size: 34)).foregroundStyle(ResetTokens.accent); Text(completed ? "The workspace was reset this day." : date > Date() ? "This day has not arrived yet." : "This past reset is still open.").foregroundStyle(FoundationTokens.muted).multilineTextAlignment(.center); if canCorrect && !completed { Button("Mark as reset") { correct() }.buttonStyle(.borderedProminent).tint(ResetTokens.action) } }.padding(28).presentationDetents([.medium]) } }
