import SwiftUI
import ResetFoundation
import ResetCore

struct ResetWelcome: View { let finish: () -> Void; var body: some View { VStack(spacing: 24) { Spacer(); Image(systemName: "arrow.triangle.2.circlepath").font(.system(size: 68)).foregroundStyle(ResetTokens.accent); Text("Reset your space").font(.largeTitle.bold()).multilineTextAlignment(.center); Text("Take two minutes to clear your desk. A calmer workspace makes a calmer start.").font(.title3).multilineTextAlignment(.center).foregroundStyle(.secondary); Spacer(); Button("Start fresh", action: finish).buttonStyle(.borderedProminent).controlSize(.large).frame(maxWidth: .infinity) }.padding(28).background(ResetTokens.wash).tint(ResetTokens.accent) } }

struct ResetToday: View { let session: ResetSession; @State private var show = false; var body: some View { ScrollView { VStack(spacing: 18) { Text("RESET").font(.caption.bold()).foregroundStyle(ResetTokens.accent).frame(maxWidth: .infinity, alignment: .leading); Text("Your desk, reset.").font(.largeTitle.bold()).frame(maxWidth: .infinity, alignment: .leading); DeskScene(level: session.progress.level, clean: session.completed); if session.completed { Text("Clear mind, clear surface.").font(.title2.bold()); Text("Today’s reset is saved. Your workspace is becoming yours.").foregroundStyle(.secondary); Button("Undo today’s reset", role: .destructive) { session.perform { try $0.undoToday() } }.buttonStyle(.bordered) } else { Text("Clear the cups, crumbs and small clutter, then sweep to reset.").multilineTextAlignment(.center).foregroundStyle(.secondary); SwipeToReset { session.perform { try $0.complete() } }; Text("One clean surface. One calmer start.").font(.callout.bold()).foregroundStyle(ResetTokens.accent) }; ResetMiniProgress(progress: session.progress) }.padding() }.background(ResetTokens.wash).sensoryFeedback(.success, trigger: session.celebration).overlay { if show { Text("Desk reset · +1 day").font(.headline).padding(20).background(.regularMaterial, in: Capsule()).transition(.scale) } }.onChange(of: session.celebration) { _, _ in guard session.completed else { return }; withAnimation { show = true }; Task { try? await Task.sleep(for: .seconds(1.2)); withAnimation { show = false } } } } }

struct SwipeToReset: View { let action: () -> Void; @State private var offset: CGFloat = 0; var body: some View { ZStack(alignment: .leading) { Capsule().fill(ResetTokens.accent.opacity(0.14)); Capsule().fill(ResetTokens.accent).frame(width: max(72, min(320, 72 + offset))); HStack { Image(systemName: "hand.draw.fill"); Text("Swipe to reset") }.font(.headline).foregroundStyle(.white).frame(maxWidth: .infinity) }.frame(height: 60).clipShape(Capsule()).gesture(DragGesture(minimumDistance: 8).onChanged { value in offset = max(0, value.translation.width) }.onEnded { value in if value.translation.width > 150 { action() }; withAnimation { offset = 0 } }).accessibilityElement(children: .combine).accessibilityLabel("Reset desk").accessibilityHint("Swipe right to confirm today’s desk reset").accessibilityAction { action() } } }

struct DeskScene: View { let level: Int; let clean: Bool; var body: some View { ZStack { RoundedRectangle(cornerRadius: 28).fill(LinearGradient(colors: [Color.white.opacity(0.8), ResetTokens.accent.opacity(0.14)], startPoint: .top, endPoint: .bottom)); VStack { HStack { Image(systemName: "sun.max.fill").foregroundStyle(.yellow); Spacer(); if level > 1 { Image(systemName: "leaf.fill").foregroundStyle(.green) } }; Spacer(); HStack(alignment: .bottom) { Image(systemName: "lamp.desk.fill").font(.system(size: 38)).foregroundStyle(.orange); Spacer(); Image(systemName: "rectangle.and.pencil.and.ellipsis").font(.system(size: 44)).foregroundStyle(ResetTokens.ink); if level > 2 { Image(systemName: "cup.and.saucer.fill").foregroundStyle(.brown) } }; RoundedRectangle(cornerRadius: 8).fill(ResetTokens.ink.opacity(0.18)).frame(height: 14) }.padding(26) }.frame(height: 210).overlay(alignment: .bottomTrailing) { if clean { Image(systemName: "checkmark.circle.fill").font(.system(size: 34)).foregroundStyle(.green).padding(18) } }.accessibilityElement(children: .ignore).accessibilityLabel(clean ? "Clean desk, reset complete" : "Desk ready for today’s reset") } }

struct ResetMiniProgress: View { let progress: ResetProgress; var body: some View { FoundationCard { HStack { Label("\(progress.streak)-day streak", systemImage: "flame.fill"); Spacer(); Text("Level \(progress.level)").font(.headline) }.foregroundStyle(ResetTokens.ink) } } }
struct ResetProgressView: View { let progress: ResetProgress; var body: some View { ScrollView { VStack(spacing: 16) { FoundationCard { VStack(alignment: .leading, spacing: 8) { Text("Your rhythm").font(.headline); Text("\(progress.streak) days").font(.system(size: 42, weight: .bold)); Text("Best streak: \(progress.bestStreak) days").foregroundStyle(.secondary) } }; FoundationCard { VStack(alignment: .leading, spacing: 12) { Text("Recent resets").font(.headline); ForEach((0..<7).reversed(), id: \.self) { i in let day = Calendar.current.date(byAdding: .day, value: -i, to: Date())!; let done = progress.history.contains(ResetDay.key(day)); HStack { Text(day, format: .dateTime.weekday(.wide)); Spacer(); Image(systemName: done ? "checkmark.circle.fill" : "circle").foregroundStyle(done ? .green : .secondary) }.accessibilityElement(children: .combine).accessibilityLabel("\(day.formatted(date: .complete, time: .omitted)), \(done ? "reset complete" : "not reset")") } } } }.padding() }.background(ResetTokens.wash) } }
struct ResetSettings: View { let session: ResetSession; @State private var confirm = false; var body: some View { Form { Section { Label("Private on this iPhone", systemImage: "lock"); Text("Reset stores only your completion history in this app. No account or sync service.").foregroundStyle(.secondary) }; Section("Fresh start") { Button("Reset progress", role: .destructive) { confirm = true } }; Section { Text("Reset · make space for a clearer mind").font(.caption).foregroundStyle(.secondary) } }.confirmationDialog("Delete all progress?", isPresented: $confirm) { Button("Delete", role: .destructive) { session.perform { try $0.reset() } }; Button("Cancel", role: .cancel) {} } message: { Text("Your reset history and streak will be permanently deleted from this iPhone.") } } }
